<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SVC_API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLayer\BusinessLayer.csproj" />
    <ProjectReference Include="..\DataBaseInteraction\DataLayer.csproj" />
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
  </ItemGroup>

</Project>
